"%dev":
  quarkus:
    dynamodb:
      endpoint-override: http://localhost:8000
    swagger-ui:
      always-include=true:
  aws:
    region: sa-east-1
    credentials:
      type: static
      static-provider:
        access-key: test-key
        secret-access-key: test-secret

"%prod":
  quarkus:
    swagger-ui:
      always-include=true:
    http:
      cors:
        ~: true
        origins: https://taskplannerweb.s3.sa-east-1.amazonaws.com

  aws:
    region: sa-east-1
    credentials:
      type: static
      static-provider:
        access-key: YOUR_AWS_ACCESS_KEY
        secret-access-key: YOUR_AWS_ACCESS_SECRET_KEY
